### ISSUE TITLE
Update masterlists to utilise prelude concept

### ISSUE THREAD

**Issue by pStyl3** [loot/loot.github.io#87]
Under https://github.com/loot/loot/issues/1492

In order for the masterlists to make use of the newly created [prelude.yaml](https://github.com/loot/prelude), a few things must be adjusted.

# Part 1
The first step is to introduce changes on the existing `v0.15` branch to start the migration process.
- [x] Add the new `prelude` node - with it's own `common` sub-node - before the existing masterlist `common` node
```yaml
prelude:
  common:

common:
bash_tags:
globals:
groups:
plugins:
```
- [x] Move everything in `masterlist.yaml`'s `common` section to the new `prelude/common` section, except for the `File Anchors` such as e.g.
```yaml
  - &SKSE
    name: '../skse_loader.exe'
    display: '[SKSE](https://skse.silverlock.org)'
```
as well as Sub-Anchors that reference Message Anchors such as e.g.
```yaml
  - &useVersionDeadMoney
    <<: *useVersion
    subs: [ 'Dead Money' ]
    condition: 'active("DeadMoney.esm")'
```
- [x] Move these existing localised messages from `masterlist.yaml`'s `globals` section
```yaml
latestLOOTThread
creationClubPlugins
scriptExtenderMissing
scriptExtenderRequiredScripts
moveNVAC
```
to `masterlist.yaml`'s `prelude/common` section too. Do this by creating new `Global Anchors` like described [here](https://github.com/loot/loot/issues/1492#issuecomment-926833794), but use the correct, non-generic & game-specific `subs` and `conditions` like they are already defined in each `masterlist.yaml` file (unlike what the generic `subs` and `conditions` in `prelude.yaml` might look like).

- [x] Add the new Sub-Anchors that reference the newly created `Global Anchors` in `masterlist.yaml`'s `globals` section like described [here](https://github.com/loot/loot/issues/1492#issuecomment-926833794).
```yaml
# Latest LOOT Thread
  - &lootThread
    <<: *latestLOOTThread
    subs: [ 'https://loot.github.io/latest-thread/' ]
```

# Part 2
The following steps will need to performed, once the next LOOT version, that amongst other things has full support for `prelude.yaml`, has been released.

- [x] Replace the localised messages in `masterlist.yaml`'s `prelude/common` section with the their new (English only) short definition counterparts like [this](https://github.com/loot/loot/issues/1492#issuecomment-922371449):
```yaml
prelude:
  common:
    # Message Anchors
    - &alreadyInX
      type: error
      content: Delete. Already included in %1%.
```
- [x] Also include the short definitions of Message Anchors, that previously had not been utilised in (each of) the masterlist(s), because through `prelude.yaml` every Message Anchors becomes available for each of the masterlists.

**Comment by pStyl3** [comment]
The `v0.17` branches have been created for the different masterlists. The next step is "Part 2" from the first post, within `v0.17` that is.

**Comment by pStyl3** [comment]
The needed changes have been applied.

**Comment by pStyl3** [comment]
Closing this issue as the needed changes have been done in the `v0.17` branches.
