### ISSUE TITLE
Moving from Google Code

### ISSUE THREAD

**Issue by Ortham** [loot/loot.github.io#9]
This issue tracks the various things that need to be done as part of moving from Google Code to GitHub. It is semi-related to the various things that need to be done as part of releasing v3, which has an issue [here](https://github.com/boss-developers/boss-code/issues/59).
- [x] Transfer wiki pages (issue #1).
- [x] Get team members set up on GitHub (issue #5).
- [x] Create a user-friendly landing page for the project (issue #6).
- [x] Close down the BOSS-Committers Google Group (issue #10).
- [x] Decommission the Google Code pages (issue #7).
- [ ] Close down the Bugzilla tracker (issue #8). This can be done after v3's release.
- [x] Update the links on BOSS's 4 Nexus pages to point to http://boss-developers.github.io.

Ideally, we'd have as little left to the last minute as possible, but I don't want to have the masterlists converted but v3 not ready for release, since that means that any further updates need to be done twice (on v2 and v3 masterlists) in the meantime.

I think that it's fairly safe to close down the Google Group ASAP, since it's only used by the Skyrim committers and they can just use the Bethsoft forum instead. Once the landing page is up here, we could actually decommission the Google Code pages immediately, and update the Nexus links at the same time.

That means all that would remain is to coordinate the masterlists being converted, the web-based masterlist search being implemented, and BOSSv3 being released. Ideally that would be in the order:
1. Masterlist search gets implemented.
2. Oblivion, Fallout 3 and Fallout NV masterlists get converted.
3. BOSS reaches release-ready status.
4. Skyrim masterlist gets converted.
5. BOSS gets released.
